### ISSUE TITLE
support for solr indexing

### ISSUE THREAD

**Issue by rewebit** [beechit/fal_securedownload#10]
Hello,

We have been using Solrfal to index documents in the TYPO3 backend and it works great. We want to secure documents to specific users. So that logged in users can find secured documents in a search, but access to the documents can not be provided to others. To this end, we have implemented extension fal_securedownload.

At first we noticed that the URL which is displayed in the search results for a logged in user was not correct. In looking at the index generated, there is no Content or Teaser text for documents which reside in the secured folder. At the end of this note are snippets out of the index for an secured and unsecured document.

The following are the URLs as seen in the front end. In both cases the user is logged in.
File as link on page (link works):
http://adventist.sdh/index.php?eID=dumpFile&t=f&f=4617&token=be33c54cdaf81179c1836b7c7adeb573c7eb478b

File as a result in a search (link fails):
http://adventist.sdh/ajax.php?ajaxID=FalSecuredownload%3A%3ApublicUrl&ajaxToken=5a748396b733eb309fcb1098a2333805ec9e7c33&eID=dumpFile&t=f&f=4617&token=db225b270cb721372a7e12a0bd982e465c201c9a

Thank you

Robert

SECURED DOC
"title": "applepie.docx",
"fileStorage": 2,
"fileUid": 4617,
"fileMimeType": "application/msword",
"fileName": "applepie.docx",
"fileSha1": "7fba41271d11029b761348fa1b57c7c613e44233",
"filePublicUrl": "ajax.php?ajaxID=FalSecuredownload%3A%3ApublicUrl&ajaxToken=e362724a2859d223a79cc61fc0708c50ac0ceca1&eID=dumpFile&t=f&f=4617&token=db225b270cb721372a7e12a0bd982e465c201c9a",
"url": "ajax.php?ajaxID=FalSecuredownload%3A%3ApublicUrl&ajaxToken=e362724a2859d223a79cc61fc0708c50ac0ceca1&eID=dumpFile&t=f&f=4617&token=db225b270cb721372a7e12a0bd982e465c201c9a",
"access": "205:1/c:1",
"id": "dd2e9ea387b818ee15525a986b5d693e1ac79502/tx_solr_file/4617/e29e14932cab011e34ceeadf30655ea8",
"site": "adventist.sdh",
"type": "tx_solr_file",
"content": "",
"teaser": "",
"description": "",

UNSECURED DOC
"title": "english.docx",
"fileStorage": 1,
"fileUid": 4494,
"fileMimeType": "application/msword",
"fileName": "english.docx",
"filePublicUrl": "fileadmin/adventist.org/files/content/english.docx",
"url": "fileadmin/adventist.org/files/content/english.docx",
"access": "c:0",
"id": "dd2e9ea387b818ee15525a986b5d693e1ac79502/tx_solr_file/4494/13efcd41224105fb62ecaf674c14cd54",
"site": "adventist.sdh",
"type": "tx_solr_file",
"content": "The...[content abbreviated]",
"teaser": "The...[content abbreviated]",
"description": "",

**Comment by beechit** [comment]
Hi Robert,

how about sponsoring this feature? € 100

Regards,
Edward

**Comment by rewebit** [comment]
Hello,

I will need to check with the team leader on this. What exactly are we
purchasing? There are three items presented in the issue posted to GitHub.
Perhaps there are other things which you will foresee as well. The question
about what we are sponsoring, will come when I speak with the team leader.

Best Regards,
Robert

**Comment by frans-beech-it** [comment]
Fixed with https://github.com/beechit/fal_securedownload/commit/e650ab92c99348e131b69381865e9ca5cf5c60c9
