### ISSUE TITLE
resize internal images

### ISSUE THREAD

**Issue by mhirdes** [beechit/fal_securedownload#100]
Hi,

first of all, thanks for developing this great extension. 

A costumer shows big images on his page, which are not public available. Now the images are not resized or processed, when they were displayed in the frontend. Is it not possible to process this hidden images or have I missed something in my setup?

Thanks a lot in advance.

Kind regards,
Marc

TYPO3 8.7.12
fal_securedownload 2.1.2

**Comment by fsaris** [comment]
Hi,

This should work. Are these images attached to the default core content elements? 

Processing of non public images works?

**Comment by mhirdes** [comment]
Hi, thanks for the fast response.

It's an usual core element - the CType is 'image'. Because it we updated this from TYPO3 6.2 we still use css_styled_content. Maybe this is a problem? If I check 'Is publicly available?' in the file storage it works as it should.

**Comment by frans-beech-it** [comment]
Hi,

If you are using css_styled_content you need to make sure you use the correct typoscipt to get the image path.

**Comment by mhirdes** [comment]
Hi, 

we didn't change their anything. So this TS is used: 
![29-03-_2018_09-53-32](https://user-images.githubusercontent.com/915162/38076830-203aaeca-3337-11e8-946c-988ea2b1aa50.png)

**Comment by mhirdes** [comment]
Hi,

do you have any hints for this?

**Comment by Anubiso** [comment]
Hi, 

having the same problem:

I am using protected images in the frontend and the dumped files are not processed/resized. 
Code: `<f:image image="{picture}" maxHeight="120" maxWidth="120"/>`
Result: `<img src="/index.php?eID=dumpFile&..." width="120" height="80" alt="">` 
The img-tag is right, but the image returned by the dumpFile-Script is wrong (4800x3200).

**Comment by fsaris** [comment]
If you disable the extension FE rendering goes okay?

**Comment by Anubiso** [comment]
After disabling the extension-setting `basic.resumable_download` the dumpFile scripts returns the correct processed image (120x80).

**Comment by Gregor-Agnes** [comment]
I had the same problem with the settings "width" and "height" of imges from f:image viewhelper: They are not resized if in not public storage. After switching to "maxWidth" and "maxHeight" the images are resized (when  `basic.resumable_download` is turned of). 
I think it should also work with "width" and "height", right?
