### ISSUE TITLE
Possible "Call to a member function getOriginalFile() on null" error

### ISSUE THREAD

**Issue by maechler** [beechit/fal_securedownload#102]
Hi 

I was just studying some of the code of your extension and I think I discovered a possible `Call to a member function getOriginalFile() on null` error.

If `$file->isDeleted()` you set `$file = null` and afterwards call `$file->getOriginalFile()`.
https://github.com/beechit/fal_securedownload/blob/master/Classes/Controller/BePublicUrlController.php#L53-L57

**Comment by frans-beech-it** [comment]
tnx for your report.
We will look into this
