### ISSUE TITLE
Configure redirects in EM for multidomain websites missing

### ISSUE THREAD

**Issue by angeloprevitali** [beechit/fal_securedownload#105]
Hello

in the EM there are two fields to redirect fe_users to the corresponding page in case they got no access. But how can it be redirected in case of a multidomain setup of a TYPO3 if there will be TWO! loginpages which has to be redirected in this case? Are there any plans or solutions concerning this case?

Any idea?

Regards,
Angelo

**Comment by fsaris** [comment]
Hi,

What you can do is to set this depending on the domain in your ext_localcon.php off your site extension.

```
$extensionConfig = unserialize($GLOBALS['TYPO3_CONF_VARS']['EXT']['extConf']['fal_securedownload']);
            
if ($domain === '....') {
    $extensionConfig['no_access_redirect_url'] = '....';
}

$GLOBALS['TYPO3_CONF_VARS']['EXT']['extConf']['fal_securedownload'] = serialize($extensionConfig);
```

**Comment by angeloprevitali** [comment]
Hi
sounds good. Good idea. I will check it out and give you feedback here on github.
Regards,
Angelo

**Comment by angeloprevitali** [comment]
Works great. So i close this one.

**Comment by thegass** [comment]
I tried to Implement this feature in https://github.com/thegass/fal_securedownload/commit/6058590882cbd3bb6ef077a5c0ca91082e78838b

works for me. don't know if it's goog enough for general use/a pullrequest
