### ISSUE TITLE
access (fe_groups) not set by default in RecordContext! (Information disclosure)

### ISSUE THREAD

**Issue by LeoniePhiline** [beechit/fal_securedownload#107]
fal_securedownload comes with the following for storage context:

```
    # Make sure the fe_groups are considered (replace __storageUid__ with your secured storage UID)
    plugin.tx_solr.index.enableFileIndexing.storageContext.__storageUid__.enableFields.accessGroups = fe_groups
```

However, there is no solution for RecordContext! 
I have set `plugin.tx_solr.index.queue.fileadmin = 0` and only want to index files referenced in content fields.

It would also be pointless to set `plugin.tx_solr.index.enableFileIndexing.recordContext.enableFields.accessGroups = fe_groups`, because `\ApacheSolrForTypo3\Solrfal\Context\RecordContext` (and `PageContext` as well) does not process `enableFields`.

The following TypoScript configuration below works for me. Please note that I have not tested it for side-effects. :)

If you think there won't be side-effects, then please add that to the `fal_securedownload` Documentation! ;)

```
plugin.tx_solr.index {
    queue {
        fileadmin = 0
       
       // 1) This part is already documented
        _FILES.default.filePublicUrl = public_url
        _FILES.default.url = public_url

       2) This part needs to be documented!
        _FILES.default.access = TEXT
        _FILES.default.access {
            wrap = r:|
            field = fe_groups
        }
    }
}
```

**Without that `_FILES.default.access` assignment, files in RecordContext will be indexed with `access: ['c:0']`! This is an information disclosure leak and thus a security issue!**

Users who are not logged in get search results to files in secure storage. (They still cannot access the file, but name, text snippets, knowledge of its existence etc.)

**Comment by fsaris** [comment]
Could you please create a PR to add this to the documentation.

If I remember correctly I solved it similar in one of our projects

**Comment by LeoniePhiline** [comment]
Update:
The previous solution produced an access field value of "r:" (without any following integer) if fe_groups of the sys_file_metadata record or its parent folders or storage were empty.

Updated solution for proper solr file access:
```
        _FILES.default.access = TEXT
        _FILES.default.access {
            value = r:0
            override {
                cObject = TEXT
                cObject {
                    required = 1
                    field = fe_groups
                    wrap = r:|
                }
            }
        }
```
