### ISSUE TITLE
Secure fileadmin subfolder only

### ISSUE THREAD

**Issue by n1klas** [beechit/fal_securedownload#109]
Is it possible to secure an subfolder "/fileadmin/secured_files/" and still have public access to "fileadmin/*"?

I already have two filestorage created with linked files. When i check "is public available" in in filesorage 1 (fileadmin) and uncheck "is public .." in filestore 2 (fileadmin/secured_files) all files in storage 2 are open for everyone 

edit: - is it possible to delete the default fileadmin storage? Without loosing files/links?

**Comment by frans-beech-it** [comment]
no it's not possible to have a second storage that's a subfolder of the first one. And deleting an existing storage is also not a good idea.

I would create a new storage with a different root (not inside of the default storage) and move all files/folders that should be protected through the backend to this new folder. Then all relations with existing content elements will be updated etc.
