### ISSUE TITLE
folder permissions in TYPO3 8.7

### ISSUE THREAD

**Issue by stlindner** [beechit/fal_securedownload#110]
I just migrated a TYPO3 website from 6.2 to 8.7. In the frontend everything works fine, but in the files module in the backend the clickmenue for folder permissions is missing.

Maybe this has to do something with a breaking change in TYPO3 8.6 (see below).

Do I miss something or is this feature since TYPO3 8.6 not available anymore?  If so, are there plans to bring it back?

And by the way: Thanks for this great extension. 

Greetings,
Stephan

--------------------------

From the file typo3/sysext/core/Documentation/Changelog/8.6/Breaking-78192-RefactorClickMenuContextMenu.rst

Hooks removed
The following two hooks have been removed:

:php:$GLOBALS['TBE_MODULES_EXT']['xMOD_alt_clickmenu']['extendCMclasses']
:php:$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['backend']['contextMenu']['disableItems']
Migration
^^^^^^^^^

Use the new ItemsProvider API to add or modify click-menu items.
See existing usage of the API in the core :php:TYPO3\CMS\Filelist\ContextMenu\ItemProviders\FileProvider or :php:\TYPO3\CMS\Beuser\ContextMenu\ItemProvider.

**Comment by tobenschmidt** [comment]
Until this is fixed you can use this workaround to add new folder permissions:

* Add a new entry to database table _tx_falsecuredownload_folder_
* Add the folder path in the selected storage with leading and trailing slashes to field _folder_
* Calculate the folder hash on the command line with  `php -r 'echo sha1("/my/path") . "\n";'` (Leading slash but no trailing slash!) and add it to field _folder_hash_
* Add uid of frontenduser group to field _fe_groups_

**Comment by frans-beech-it** [comment]
in the top toolbar of the folder you can also find a button to access the folder settings:

![image](https://user-images.githubusercontent.com/4436635/51059251-d49bf800-15eb-11e9-93d0-28e8426b1de6.png)

**Comment by frans-beech-it** [comment]
Fixed with a995d72c66ab02a8b2a65e2ae698c392b1877ffd

**Comment by tobenschmidt** [comment]
> in the top toolbar of the folder you can also find a button to access the folder settings:
> 
> ![image](https://user-images.githubusercontent.com/4436635/51059251-d49bf800-15eb-11e9-93d0-28e8426b1de6.png)

:astonished: You're right. There is is indeed a button for folder settings. I totally overlooked this. Still it's great to see that the context menu is back. Thanks!

**Comment by fsaris** [comment]
It's also part of the documentation now :smile:
