### ISSUE TITLE
TER isn't up-to-date, shows 2.0.1 (instead of 2.1.2)

### ISSUE THREAD

**Issue by gaumondp** [beechit/fal_securedownload#111]
I would suggest you also update TER version from time to time. Not everyone goes at the source for the latest version...

And thanks for the extension !

**Comment by echavaillaz** [comment]
And now the version 3 is released but not in the TER.

**Comment by fsaris** [comment]
Latest version is released to TER 

https://extensions.typo3.org/extension/fal_securedownload/
