### ISSUE TITLE
Folder icon is not visible in FileTree/Leaf.html

### ISSUE THREAD

**Issue by gaumondp** [beechit/fal_securedownload#112]
TYPO3 8.7.19, using 2.0.1 (TER) or GIT version (2.1.2) of the extension, the HTML is generated in FE but no icon is visible for folders (Resources/Private/Partials/FileTree/Leaf.html)

`<span class="icon-folder icon-folder-open" data-folder="2:/secure/under/">under</span>`

The JS is included thru the extension TS template but still no folder icon in FE, just a basic `<li>`.

**Comment by frans-beech-it** [comment]
icons can be added through css. This currently isn't added by the extension itself. Template is prepared for use with fontawesome

**Comment by gaumondp** [comment]
For anyone with the same problem this is how to make it works:

First of all it's "compatible" with FontAwesome 3.2, not current v5.

Just add this line in your SETUP TS template:
page.headTag =  <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">

This little information could be added to the documentation.

**Comment by frans-beech-it** [comment]
We are open voor pull requests to improve the documentation. Also for pull requests that update the templates to use the new icons
