### ISSUE TITLE
TYPO3 9 compatibility planned?

### ISSUE THREAD

**Issue by yurianu** [beechit/fal_securedownload#113]
Will fal_securedownload get a TYPO3 9 version? A lot of the code doesn't work anymore with TYPO3 9.

**Comment by noll1** [comment]
+1

**Comment by bobbel78** [comment]
Hi Frans,

how much sponsoring do you need to get the project going?

Best regards,
Dominik

**Comment by bobbel78** [comment]
Willing to sponsor 1 or 1,5 hours. Anyone else around?

**Comment by tritum** [comment]
If bobbel78 sponsors 1,5 hours, we sponsor 1,5 hours as well. Deal?

**Comment by tritum** [comment]
@frans-beech-it would be great to get a some "social love" for sponsoring ;)

**Comment by tritum** [comment]
Yes @frans-beech-it, invoice would be great! And thanks @bobbel78!

**Comment by frans-beech-it** [comment]
Hi, 

Tnx for stepping in. Invoice will be no problem. And the social love part is the least we can do for it :)

Our planning is to work next week on this. Would that fit your planning?

Frans

**Comment by bobbel78** [comment]
Hi,
sounds very good!
Dominik

**Comment by Anuorin** [comment]
We also need the v9 version for a current project.
@frans-beech-it Would be great if you could tell us the expected release date

**Comment by TritumFlinke** [comment]
We used the PR https://github.com/beechit/fal_securedownload/pull/114 in our T3v9 project and it worked fine. There is a deprecation left witch will probably prevent it from working under v10 but for v9 it works.

**Comment by madaxel** [comment]
Hi @TritumFlinke thanks for the info. We installed that branch too, but were not sure about the WIP comments.

If it is working, please merge and do a TER update @frans-beech-it  the deprecation could be removed later I think.

**Comment by frans-beech-it** [comment]
Sorry for the delay. 

Current master is now compatible with 8LTS and 9LTS (tnx @bjo3rnf for most of the work). The deprecation's will stay for a while. (probably until we drop 8LTS support).

Would be cool if you could test current master. Will release a version to TER next week.

**Comment by bobbel78** [comment]
@frans-beech-it Dominik Müller, webfacemedia
thx!
