### ISSUE TITLE
Folder permissions not visible

### ISSUE THREAD

**Issue by Vik29** [beechit/fal_securedownload#118]
Looks like the problem discussed here
https://github.com/beechit/fal_securedownload/issues/110
is still a thing in Typo3 v9.5.3

I'm not seeing any folder permissions in the filelist. Not in the submenu nor in the toolbar.

**Comment by fsaris** [comment]
Did you turn the filestorage to `not public`?

What version of the extension are you using?

**Comment by Vik29** [comment]
> Did you turn the filestorage to not public?
Yes

> What version of the extension are you using?
2.1.3

**Comment by fsaris** [comment]
Did you clear cache and reload the backend.

Could you maybe add a screenshot of the file list with the root folder of the non public filestorage selected?

**Comment by Vik29** [comment]
Yes, i cleared the cache several times.
Screenshot attached
![filelist](https://user-images.githubusercontent.com/30268417/54589462-fa97ab80-4a25-11e9-8a05-ba467768023a.PNG)

**Comment by frans-beech-it** [comment]
ah, you are not on the latest version. You need to update to v2.2.0

**Comment by Vik29** [comment]
I was using the version from the repository. The latest version worked for me. Thx
