### ISSUE TITLE
Adding Frontend File Manager features

### ISSUE THREAD

**Issue by Lumrenion** [beechit/fal_securedownload#12]
This extension already implements the Features of a Frontend File Manager half the way, so it could probably be extended with Features as
* Upload files as a Frontend user 
* Upload and extract ZIP files as a Frontend user
* Select and Download multiple files as ZIP 
* view and edit File Name and Description in the Frontend 
* Delete Files/Folders as a Frontend user 
* (move files as a Frontend user) 

I hope this functionality is even desired. As for myself I would highly appreciate this development. 

Best regards 
Philipp

**Comment by fsaris** [comment]
These are indeed nice features but out of scope for this extension. Would be a nice candidate for a separate extension depending on this extension.
