### ISSUE TITLE
new feature (simple) get file description

### ISSUE THREAD

**Issue by gilas1959** [beechit/fal_securedownload#13]
Hi 
I'm not an expert, but I tried to modify the template so I supposed that to add che content of sys_file description, I should use the 'description' field.

Unfortunately there is non (apparent) way to do it. Adding the variable {description} or {file.description} no output is given.

I modified the template file:

typo3conf/ext/fal_securedownload/Resources/Private/Partials/FileTree/Leaf.html

adding i.e. {file.description} or {description} variable

without success.

where I'm wrong? I believe the best way to give info to downloaders is to printout

name, size, description

so the downloader knows what file to select.

thank you much for your help

**Comment by fsaris** [comment]
Try {file.properties.description}.

To see what properties are available you could use <f:debug>{file.properties}</f:debug>

Gr. Frans

**Comment by gilas1959** [comment]
Hi Frans
monday I'll try what you suggest.
Thank you very much for your nice and useful extension and answer.

Kind regards!
