### ISSUE TITLE
Setting folder permissions in filelist for editors

### ISSUE THREAD

**Issue by kheinzel** [beechit/fal_securedownload#141]
For admins it works fine - but for editors it is not possible to edit folder permissions in the filelist. And I can't find any settings concerning this.

**Comment by kpnielsen** [comment]
Same issue here in TYPO3 v10.4.21. Non-admin users can, in the filelist module, click on the "Edit folder Permissions" icon but then the module just starts loading and hangs up.

**Comment by RaHaenni** [comment]
Is there a fix or workaround for this issue yet? 
I've run into the same Problem and I don't want to give the editors admin rights on the site just for this.
The site runs on Typo3 v10.4.31 with fal_securedownload v3.0.2.

**Comment by FamousWolf** [comment]
@RaHaenni I just checked and it should work in 3.0.2 as long as the user has the correct access rights. You need to give the users edit access to the Folder configuration table. Also the user needs to have read access to the user groups and the folder the user groups are in.
