### ISSUE TITLE
Question: What are your plans regading TYPO3 v10

### ISSUE THREAD

**Issue by michaelof** [beechit/fal_securedownload#142]
Hi,

I'm using your cool extensions for a small and non-commercial website. Mainly elementary school crossing guards securely (GDPR, private data) downloading their spreadsheet / pdf based schedules. 

I remember that moving fal_securedownload from v8 to v9 was non-trivial for you, will it be the same for the step from v9 to v10? Any planned roadmap?

Thank you very much,
Michael

**Comment by frans-beech-it** [comment]
Hi Michael,

Yes our intention is to have the extension compatible with V10. But we do not have this really planned yet. Depends on when we have a project our self or when someone steps in to help (code or sponsoring).

Kind Regards,
Frans

**Comment by baschny** [comment]
Hey @frans-beech-it! What would you expect to be the required budget to bring this extension up to date with latest TYPO3 v10? You could also answer me directly if you want to (eb@cron.eu). Thanks!

**Comment by maritwho** [comment]
@frans-beech-it @baschny 

Hi, I am also interested in the current state of the TYPO3 10 update. Maybe we can work together to make this extension compatible with TYPO3 10. We use this extension and want to use it for new projects as well. Please contact me here or personal (sebastian.hofer@pluswerk.ag).

Thanks :-).

**Comment by EdwardLenssen** [comment]
@maritwho 

Hi Sebastian,

thanks for request.

See your mailbox.

See #147

New release expected latest in September.

**Comment by rungissan** [comment]
Hi guys. It  took me  5 min for updating the extension to the version 10.  All you need to know on the page  https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.0/Breaking-82414-RemoveCMSBaseViewHelperClasses.html

**Comment by joey-beech-it** [comment]
> Hi guys. It took me 5 min for updating the extension to the version 10. All you need to know is on the page https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.0/Breaking-82414-RemoveCMSBaseViewHelperClasses.html

@rungissan Thanks, but this was not enough for version 10, only for version 9.

**Comment by joey-beech-it** [comment]
@maritwho, @michaelof, @baschny 

There has been made a pull request which (should) be fully working for V10
https://github.com/beechit/fal_securedownload/pull/149

If you could also verify/test then this will be made ready for release. 

Thanks

**Comment by fsaris** [comment]
new compatible version is released
