### ISSUE TITLE
Make output of FAL-{file.title} possible in fluid template

### ISSUE THREAD

**Issue by notarocketscientist** [beechit/fal_securedownload#15]
Hello everybody, 

nice extension. Saves me a lot of time in my current project.
But I miss the possibility to display the file-title (if one is set in FAL) in the sd:downloadLink-Viewhelper (Leaf.html)

When I dump {file} with f:debug, I see, that the title is stored "mediaDataproperties" - but I can not access it like this:

    <li><span class="icon-file icon-file-{file.extension}"></span><sd:downloadLink file="{file}">{file.title}</sd:downloadLink></li>

I also tried {file.metaDataProperties.title} but it seems to be protected or something (?).

My customer uploads his files with really ugly filenames and I give them all nice titles. It would be super nice, if you could implement this litte feature.

Thank you.

**Comment by frans-beech-it** [comment]
You can use `{file.properties.title}` to get the title.

gr. Frans

**Comment by notarocketscientist** [comment]
Thank you. My fault: this is what happens when you are working until late at night.
Works like a charm now!

Nice!
