### ISSUE TITLE
TypoScriptFrontendController was tried to be injected before initial creation

### ISSUE THREAD

**Issue by echavaillaz** [beechit/fal_securedownload#150]
Hi,

When using a link like `t3://page?uid=...` as `login_redirect_url` or `no_access_redirect_url` there is a fatal error when trying to access a file without having access : `TypoScriptFrontendController was tried to be injected before initial creation`.

Can you have a look please?

Thanks,
Eric

**Comment by fsaris** [comment]
Hi, wat version of the extension and TYPO3 did you use?

**Comment by echavaillaz** [comment]
Hi,

3.0.0 for fal_securedownload with latest TYPO3 10.

Thanks,
Eric

**Comment by joey-beech-it** [comment]
Hi,

We have added this issue into our planning and will try to solve it soon.

**Comment by echavaillaz** [comment]
Ok, thanks.

**Comment by joey-beech-it** [comment]
@echavaillaz to give you an update.
We are able to look at this next week.

**Comment by joey-beech-it** [comment]
After some research we've found out that this issue might be more complex than expected, due too a busy schedule we won't be able to look for a fix until next week.

In the meantime please use url's instead of a typolink for forwarding to a page, we've confirmed this does work.

**Comment by dhuf** [comment]
Not sure about the implications, but replacing

`$contentObject = GeneralUtility::makeInstance(ContentObjectRenderer::class);`
with
`$contentObject = new ContentObjectRenderer();`

seems to fix the issue at least under v10

**Comment by joey-beech-it** [comment]
As @FamousWolf said. 

> This will fix it for t3://page?uid=... links. However this could still break when using custom t3://... links. When resolving these links tsfe is passed to the resolving class. This fix sets that to null. As tsfe can explicitly be null in the ContentObjectRenderer constructor, any custom t3://... link resolving classes should check for this, but if it doesn't this will cause an error.

Since it doesn't work at all now we will accept this pull request, since this is an improvement.
