### ISSUE TITLE
Add supported PHP versions information to composer.json

### ISSUE THREAD

**Issue by marclindemann** [beechit/fal_securedownload#154]
thanks 👍

**Comment by christophlehmann** [comment]
Does it need to be mentioned? It requires TYPO3 10.4 which depends on PHP ^7.2

**Comment by LeoniePhiline** [comment]
Version 4 [requires PHP 8](https://github.com/beechit/fal_securedownload/compare/3.0.0...4.0.0#diff-3de250d1818a56833f6b2eccbebf8992e17e45d2a4776568f93d2a0e1b22cc19R248).

This should definitely be declared in `composer.json`, as TYPO3 11 still supports PHP 7.4.

**Comment by joey-beech-it** [comment]
@FamousWolf

**Comment by FamousWolf** [comment]
Version 4 should work with PHP 7.4. The changes that were done to require PHP 8 were reverted in https://github.com/beechit/fal_securedownload/commit/02ce8f1df9a9fe650b7cba8c747cafa060df7b1f. If it doesn't work with PHP 7.4, then it's a bug.

**Comment by LeoniePhiline** [comment]
I believe not everything was reverted:

![image](https://user-images.githubusercontent.com/22329650/166335924-0946784a-9825-4f97-a24d-7214c0b5eb54.jpeg)

**Comment by FamousWolf** [comment]
@LeoniePhiline I've create a new issue for PHP 7.4 compatibility (#177).

**Comment by sgrossberndt** [comment]
As discussed [in the TYPO3 v12 compatibility pull request](https://github.com/beechit/fal_securedownload/pull/210#discussion_r1229632610) there is a polyfill and this is not a problem for PHP 7.4.

This issue can be closed.
