### ISSUE TITLE
Define extension key in composer.json

### ISSUE THREAD

**Issue by NochEinKamel** [beechit/fal_securedownload#159]
Composer is spamming me with deprecation warnings:

TYPO3 Extension Package "beechit/fal-securedownload", does not define extension key in composer.json.
Specifying the extension key will be mandatory in future versions of TYPO3 (see: https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/ComposerJson/Index.html#extra)

Thanks.

**Comment by joey-beech-it** [comment]
This will be in the new release. Thanks

**Comment by joey-beech-it** [comment]
This will be in the new release. Thanks
