### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by netengine-at** [beechit/fal_securedownload#164]
Hello!

I'm trying to get fal_securedownload working with the SOLR Extension. In the documentation there is a part "EXT:solrfal support" which I have integrated in my TYPOSCRIPT setup. Unfortunately, the access field in SOLR is always the same => "access":["r:0"] and therefore all files are listed in the search. Only when I click on a link to a file that I may not view, do I get the expected error message.

I am also not sure about the solrfal Extension, I can't find it in the TYPO3 Extension Repository.

At the moment I am using the following Extensions:
solr - Apache Solr for TYPO3 - Enterprise Search 
solr_file_indexer - Solr file indexing
tika - Apache Tika for TYPO3
fal_securedownload - FAL Secure Download

I would be very thankful for any help!

**Comment by netengine-at** [comment]
Hi,

I'm also getting URLs in the search results which don't seem to work, any ideas?

https://www.test.com/
typo3/
index.php
?route=%2Fajax%2Ffal_securedownloads%2Fdump_file&
token=567faf313b973e7704318952dd48c0e839dd9ecd&
eID=dumpFile&
t=f&
f=11406&
fal_token=dbd5b24432a05dc9803758dcb5a81ce1adb1132

**Comment by joey-beech-it** [comment]
@netengine-at 

What version of fal_securedownload are you using. Could you check if your issue is related to https://github.com/beechit/fal_securedownload/issues/161 and see if the pull request linked by @FamousWolf solved your issue?

EXT:solrfal is a members only extension and not public.

**Comment by netengine-at** [comment]
sorry, forgot all the versions!

I'm making some changes to the Extension so it work's with solr_file_indexer. So far I've made a small change to generatePublicUrl and now I've just got to get the files user-group into Solr...
