### ISSUE TITLE
Extension key missing in composer.json

### ISSUE THREAD

**Issue by marble** [beechit/fal_securedownload#174]
composer is telling me:
"""The TYPO3 extension package "beechit/fal-securedownload", does not define an extension key in its composer.json. Please report this to the author of this package. Specifying the extension key will be mandatory in future versions of TYPO3 (see: https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/ComposerJson/Index.html#extra)
"""

**Comment by FamousWolf** [comment]
It's been fixed in master. We'll probably release a new version at the end of the week.
