### ISSUE TITLE
PHP 7.4 compatibility

### ISSUE THREAD

**Issue by FamousWolf** [beechit/fal_securedownload#177]
The last release the extension is only compatible with PHP 8.0, not 7.4. At least in `BeechIt\FalSecuredownload\Security\CheckPermissions` the function `str_contains` is used, which was added in PHP 8.0. The extension needs to be checked for other things that are not compatible with PHP 7.4.

**Comment by FamousWolf** [comment]
@LeoniePhiline As far as I can see 4.0.0 works properly in PHP 7.4. `str_contains` is a PHP 8 function, but has been polyfilled using the `symfony/polyfill-php80` package which is included by TYPO3 core. The core also uses this function a lot. Do you have any other problems with PHP 7.4?

**Comment by LeoniePhiline** [comment]
Hi @FamousWolf 

Not specifically. I had inspected the code in advance to see where issues might occur. Due to the php8 function, I held off with upgrading, but thanks to the polyfill I can go ahead.

If anything comes up, I think it's best to open a new ticket.
