### ISSUE TITLE
PHP Warning: Trying to access array offset on value of type null in BackendUserAuthentication.php line 1502

### ISSUE THREAD

**Issue by marclindemann** [beechit/fal_securedownload#180]
if extension is active, following warning exists at login page from backend:

` #1476107295 TYPO3\CMS\Core\Error\Exception
PHP Warning: Trying to access array offset on value of type null in vendor/typo3/cms-core/Classes/Authentication/BackendUserAuthentication.php line 1502`

it seems that DocHeaderButtonsHook is responsible for it

**Comment by FamousWolf** [comment]
Your pull request fixes the problem and has been merged. Thanks.
