### ISSUE TITLE
Uncaught TypeError: top.rawurlencode is not a function

### ISSUE THREAD

**Issue by tucBa** [beechit/fal_securedownload#181]
Typo3 version 11.5.9
Extension version: 4.0.0

If i select "Folder permissons" in context menu nothing happens.

Error:
Uncaught TypeError: top.rawurlencode is not a function
(fal_securedownload/Resources/Public/JavaScript/ContextMenuActions.js Line 43)

**Comment by FamousWolf** [comment]
This has been fixed and will be included in the next release. Thanks
