### ISSUE TITLE
Tag latest 10.4 available state?

### ISSUE THREAD

**Issue by DanielSiepmann** [beechit/fal_securedownload#185]
Hey all,

there were some changes after v3.0.0 which would be valuable for our installation.
The next release was v4.0.0 which only states compatibility with TYPO3 v11.5.

It would be cool if commit 5975fec could be tagged as v3.0.1 or v3.1.0 so one can require that as latest stable version for TYPO3 v10.4 installations.

It is not possible to use `composer req beechit/fal-securedownload:dev-master#5975fec` due to: https://getcomposer.org/doc/articles/troubleshooting.md#i-have-locked-a-dependency-to-a-specific-commit-but-get-unexpected-results- so we can't properly install the corresponding version / state.

**Comment by FamousWolf** [comment]
I've created a separate branch for TYPO3 v10.4. The latest version from that branch has been released as 3.0.2 (something went wrong with 3.0.1).
