### ISSUE TITLE
Thumbnail in backend not working

### ISSUE THREAD

**Issue by FamousWolf** [beechit/fal_securedownload#186]
TYPO3 version: 11.5.10
PHP version: 8.0.18

**Description**
In the filelist in the backend if thumbnails are enabled, it does not show thumbnails in a non-public file storage. This is because only frontend user(group)s are checked. There should also be a check for backend users if the user is logged in the backend.

**Possible problems**
What if a user is logged in the backend and has access to the non-public storage folder, but shouldn't have access in the frontend? If there's a check on backend user this user will also have access in the frontend.

**Comment by michael-binder** [comment]
I created a patch from #189 and tested it in my system (TYPO3 11.5.13 | PHP 8.1 | FAL SecureDownload 4.0) and it works like a charm.
