### ISSUE TITLE
Extension key for version 3.0.0

### ISSUE THREAD

**Issue by urz-hgw** [beechit/fal_securedownload#190]
Hi,

the extension key is missing in composer.json for version 3.0.0 for TYPO3 10.
Could you please add this for this version as well?

Thanks
Daniel

**Comment by uv21** [comment]
yes, please add extension key. Many still use Typo3 10.4
thanks too

**Comment by FamousWolf** [comment]
I've created a separate branch for TYPO3 v10.4. The latest version from that branch has been released as 3.0.2 (something went wrong with 3.0.1).

**Comment by urz-hgw** [comment]
Thanks!
