### ISSUE TITLE
Link Folder permissions in File List not Clickable

### ISSUE THREAD

**Issue by anderlk** [beechit/fal_securedownload#191]
In the file list the menu item Folder Permissions is not clickable. The menu item in the button bar works without problems.

Tested under TYPO3 11.5.13.

![Bildschirmfoto 2022-08-06 um 17 59 16](https://user-images.githubusercontent.com/12695520/183256733-221a62ea-5df0-4a36-8b42-f8518e39d938.png)

**Comment by FamousWolf** [comment]
I can not reproduce this in the current master. Can you check if it's still an issue in the just released 4.0.1 version? If so, can you give me some more information. Which PHP version are you using? Which browser?

**Comment by anderlk** [comment]
In 4.0.1 the Problem is solved. The Link is clickable.

Regards Andreas
