### ISSUE TITLE
TYPO3 backend login broken with TYPO3 v11 and php 8

### ISSUE THREAD

**Issue by bigahuna** [beechit/fal_securedownload#192]
After upgrade to php 8.0 / 8.1 the TYPO3 backend login (https://my.ddev.site/typo3/login) is no longer possible. 
I get the following error

`#1476107295 TYPO3\CMS\Core\Error\Exception
PHP Warning: Trying to access array offset on value of type null in /var/www/html/public/typo3/sysext/core/Classes/Authentication/BackendUserAuthentication.php line 1505`

Versions:
- TYPO3 11.5.14
- beechit/fal-securedownload 4.0.0
- php 8.0.21 (also testet with the latest 8.1 version, same behaviour)
- all run inside a ddev environment (1.19.5)

If I remove fal-securedownload, the login is working again.

Regards
Mike

**Comment by sterborg** [comment]
I can confirm this.

**Comment by FamousWolf** [comment]
This was already fixed in the master branch. I've just released version 4.0.1, which contains the fix.
