### ISSUE TITLE
File permissions buttons in file list do not work for TYPO3 7 LTS

### ISSUE THREAD

**Issue by fsaris** [beechit/fal_securedownload#20]

**Comment by fsaris** [comment]
see https://bitbucket.org/franssaris/fs_media_gallery/commits/1cc72e70994bb5dbc8c839d89919c605ea0df347 for an example to get it working in CMS 7

**Comment by camrun91** [comment]
Planning on taking a look at this today. Will branch and do pull request once updated.

**Comment by camrun91** [comment]
Just submitted a pull request I think I got all the changes needed.

**Comment by InvisibleKind** [comment]
Are there any plans to fix this? Extension claims to be compatible with 7LTS, but in fact this issue makes it not usable at all on a TYPO3 7.

**Comment by RonMen** [comment]
Hi there,
using Typo3 7 LTS it isn't working in file list to get permissions shown, also not using the pull request from @camrun91. Any other fixes?

**Comment by fsaris** [comment]
Fixed with 63597f2
