### ISSUE TITLE
Backend preview information summed up

### ISSUE THREAD

**Issue by dertimon** [beechit/fal_securedownload#201]
Hi there,
first of all thank you for your great extension.

With TYPO3 11.5.15, PHP 7.4.30 and fal_securedownload 4.0.1 the information in our backend is summed up if there's more than on plugin on a page.
I guess it's BeechIt\FalSecuredownload\Hooks\CmsLayout is instaniated only once and the summary is stored in a class property named $tableData.
Changing this to a simple variable passed to BeechIt\FalSecuredownload\Hooks\CmsLayout->renderSettingsAsTable fixes the problem.

I could provide a pull request if you like.

![Summed up data](https://echo3.de/SummedUpData.png)

**Comment by support-beech** [comment]
@dertimon A pull request would be nice. Thanks
