### ISSUE TITLE
Exception "Folder "[name]" does not exist in "/path/to/parent/[name]" when cut and paste a folder

### ISSUE THREAD

**Issue by sdelcroix** [beechit/fal_securedownload#206]
Hi,

in TYPO3 v11, when we cut a folder and paste it in the destination folder, an exception is thrown.

```
#1329836110 InvalidArgumentException
Folder "test" does not exist in "/Public/Icones/test/"
```

The error occurs in FolderChangedEventListener.php line 73 :
```PHP
$newFolder = $event->getTargetFolder()->getSubfolder($event->getTargetFolder()->getName());
```

There's no need to get the subfolder of the target folder 'cause getTargetFolder() already returns the new folder.
So this simple following change seems to fix the issue :
```PHP
$newFolder = $event->getTargetFolder();
```

**Comment by FamousWolf** [comment]
Thanks. I've implemented and tested your solution. It will be included in the next release.
