### ISSUE TITLE
12 LTS Compatibility

### ISSUE THREAD

**Issue by JenHa** [beechit/fal_securedownload#208]
Are there any plans for 12 LTS compatibilty?

**Comment by linawolf** [comment]
We would also be very interested

**Comment by AlexKvrlp** [comment]
I added a Pull request for TYPO3 12 LTS Compatibility. There are only a few changes. Feel free to test it.
https://github.com/beechit/fal_securedownload/pull/209

**Comment by linawolf** [comment]
Wow cool, that was fast!

**Comment by support-beech** [comment]
@AlexKvrlp 

I will add this to the planning of one of our developers to test this next week.
If working as expected we will make a release.

Any feedback is welcome, so we encourage others to test it too.

**Comment by AlexKvrlp** [comment]
@support-beech 
Fine, thanks!  Just tested it on TYPO3 12.4.1 and PHP 8.1.19. No problems so far...

**Comment by support-beech** [comment]
Unfortunately we weren't able to pick this up last week. We've got it planned for tomorrow now.

**Comment by AlexKvrlp** [comment]
> I've tested it, but the database tables aren't created. It could be a problem in my installation though. I'll see if I can find the problem tomorrow or Friday.

I did some more testing. I removed the extension using ` composer remove beechit/fal-securedownload && vendor/bin/typo3 database:updateschema  "*" --verbose` and the tables were gone. 
Then I reinstalled the extention using  ` composer require beechit/fal-securedownload && vendor/bin/typo3 database:updateschema  "*" --verbose` and the tables were created. 

Tested on TYPO3 12.4.1 and PHP 8.1.19.

Just to clarify: We are talking about installing the extension or is there any other process which creates tables?

**Comment by AlexKvrlp** [comment]
fine, thanks :-) . If I can support you, feel free to contact me.

**Comment by RZivaralam** [comment]
I would like to know when this plugin will be compatible with Typo 3 version 12?

**Comment by FamousWolf** [comment]
The PR is still missing a few things. Once they have been added we will test it again.

**Comment by FamousWolf** [comment]
PR https://github.com/beechit/fal_securedownload/pull/210 has now been merged to the master branch. We will do a few more tests before making a new release, but you can now use the master branch with TYPO3 12. If you find any bugs, please let us know.

Thanks to @sgrossberndt
