### ISSUE TITLE
PDF Image Preview

### ISSUE THREAD

**Issue by mkrappitz** [beechit/fal_securedownload#214]
We are having PDFs in a EXT:fal_securedownload protected folder using them (after frontend login) in core textmedia Elements for a preview image of the PDF that then links to the download. 

When you overwrite these PDFs in the fileadmin with different file content under the same file name, the preview image in the text media elements "goes blank" (the eID script in <img src="/index.php?eID=dumpFile&t=f&f=396&token=..." ...  delivers 0 bytes, but here is no errors) until the cache is cleared. After cache clearing there is again a preview image in the text media element. This behaviour is reproducable on TYPO3 11.5.30 and php 8.2 on Mittwald managed server hosting.

**Comment by joey-bolts** [comment]
@mkrappitz 

Could you test this function also without the use of fal_securedownload. I've experiences this before with just the core on several occasions. When files change, the cache is not always (correctly) flushed on the pages. 

If this also occurs in just the core then the issue should be fixed there.

**Comment by mkrappitz** [comment]
Yes, you are right. Also happens with EXT:fal_securedownload not installed. So let's close this, it's a core issue I suppose.
