### ISSUE TITLE
Exception when moving a folder

### ISSUE THREAD

**Issue by christophlehmann** [beechit/fal_securedownload#215]
When moving a folder to a parent folder i get that exception:

`InvalidArgumentException: Folder "Downloads" does not exist in "/user_upload/test/Downloads/"`

<img width="1124" alt="stacktrace" src="https://github.com/beechit/fal_securedownload/assets/4953689/10e73676-8de4-464c-8375-0109a996aa30">
<img width="652" alt="body" src="https://github.com/beechit/fal_securedownload/assets/4953689/66cc25d7-c693-4577-ae5a-ef7a241210ea">

Shouldn't `$newFolder = $event->getTargetFolder()->getSubfolder($event->getTargetFolder()->getName());` better be `$newFolder = $event->getTargetFolder());` ?

TYPO3 ^11.5
fal_securedownload 4.0.3

**Comment by joey-bolts** [comment]
Thanks for the issue. We will try to look into this asap.

**Comment by joey-bolts** [comment]
@christophlehmann 

It seems this has been fixed in the lastest master branch. We will do a release soon which should both support 11 & 12
Could u test the latest version on master branch?

**Comment by sdelcroix** [comment]
Duplicata of #206 ;)

**Comment by support-beech** [comment]
Solved in https://github.com/beechit/fal_securedownload/issues/206
