### ISSUE TITLE
503 error on file indexing with ke_search

### ISSUE THREAD

**Issue by vmans** [beechit/fal_securedownload#219]
12LTS; Latest versions of ke_search and fal_securedownload

It concerns indexing of PDF files. Without the fal_securedownload is goes well (however I have not tested that with the directory outside the webroot as it is during the error situation) but with it, it goes like Oops....

503

BeechIt\FalSecuredownload\Hooks\KeSearchFilesHook::modifyFileIndexEntry(): Argument #5 ($indexer) must be of type tx_kesearch_indexer_types_file, Tpwd\KeSearch\Indexer\Types\File given, called in /var/www/clients/client17/web80/web/vendor/tpwd/ke_search/Classes/Indexer/Types/File.php on line 465

**Comment by FamousWolf** [comment]
@vmans Can you check if it works with the current master?

**Comment by vmans** [comment]
@FamousWolf I have installed the dev-master (and checked if the source is really updated) and unfortunately, the error is still exactly the same.

**Comment by FamousWolf** [comment]
I'll take a look at this this week

**Comment by mbsued** [comment]
Error happens also in Typo3-Installation 11,5.31:
Uncaught TYPO3 Exception Argument 3 passed to BeechIt\FalSecuredownload\Hooks\KeSearchFilesHook::modifyFileIndexEntryFromContentIndexer() must be an instance of tx_kesearch_indexer_types_file, instance of Tpwd\KeSearch\Indexer\Types\File given, called in /html/typo3/typo3conf/ext/ke_search/Classes/Indexer/Types/Page.php on line 1208
thrown in file /html/typo3/typo3conf/ext/fal_securedownload/Classes/Hooks/KeSearchFilesHook.php
in line 59

**Comment by FamousWolf** [comment]
@mbsued Can you test this PR https://github.com/beechit/fal_securedownload/pull/224? This should fix it, but I don't have an installation with ke_search to test it on.

**Comment by vmans** [comment]
Thanks! No error anymore in 12LTS.
