### ISSUE TITLE
RealURL support

### ISSUE THREAD

**Issue by seirerman** [beechit/fal_securedownload#22]
Would be nice to have.

**Comment by Norcoen** [comment]
Supporting realurl would be really nice

**Comment by mgrn0** [comment]
+1

**Comment by liayn** [comment]
What do you expect the URLs to look like? Any suggestions?

**Comment by mgrn0** [comment]
it would be very nice to get rid of the / replace string "index.php?eID=dumpFile" - eventually with a string the site manager/programmer can define?

**Comment by liayn** [comment]
Well, eID scripts are handled completely separated. Hence realurl never comes into the game!
There is NO way to rewrite an arbitrary URL to an eID URL.
You can only solve that at server level, like described here: https://docs.typo3.org/typo3cms/extensions/dd_googlesitemap/2.1.0/ExtGoogleSitemap/Administration/BetterNameForTheSitemap/Index.html

**Comment by Norcoen** [comment]
That's actually pretty clever, totally forgot about this even though I used to hide some .php script as .jpg or .png

**Comment by fsaris** [comment]
Closed this issue for now as I currently don't see a general solution for this.
