### ISSUE TITLE
Missing table fields

### ISSUE THREAD

**Issue by infabo** [beechit/fal_securedownload#220]
I guess ext_tables.sql was cleaned too much in 2dc2d908f7e6dd63916a5acdf8ad8667b47ab331.

There is no TCA for `tx_falsecuredownload_download`, so there is are not default system columns created by TYPO3.

![image](https://github.com/beechit/fal_securedownload/assets/3999104/0dadfc43-3113-4241-86c4-1df41d2ce78b)

Version: 5.0.1

**Comment by FamousWolf** [comment]
I'll take a look at it this week.
