### ISSUE TITLE
Table-definition of tx_falsecuredownload_download does not fit to TCA-definition of the table

### ISSUE THREAD

**Issue by mbsued** [beechit/fal_securedownload#228]
The definition of the table tx_falsecuredownload_download does not fit to the TCA of the table. The field for the user is named feuser in the sql-file, in the tca-file it is named fe_user.

**Comment by support-beech** [comment]
@mbsued Issue solved. https://github.com/beechit/fal_securedownload/commit/836b11738b6544358c278a1a49aa6a269fc1d933
