### ISSUE TITLE
Non-admin can't preview files

### ISSUE THREAD

**Issue by Rinxiao** [beechit/fal_securedownload#229]
TYPO3 Version: 12.4.7
Extension Version: 5.0.4
PHP Version: 8.2.8

I took the following actions:
- Install extension via composer req
- Added a second sys_file_storage (not public) and sys_filemount
- Created a physical folder outside of my document root
- Added the new filemount to my general backend editor group's file_mountpoints
- Switched to the backend view of one of those editors (non-admin) to check if they have access

They have access to the folder and can upload files. However, the preview does not work.
<img width="619" alt="image" src="https://github.com/beechit/fal_securedownload/assets/72814604/a2efefb6-c102-48ef-91be-c491d83d5ab9">

When I try to open the file in list view by clicking the "show" button, I receive the following error message:

```
TYPO3\CMS\Core\Error\Exception

PHP Warning: Undefined array key "base" in [...]fal-securedownload/Classes/Security/CheckPermissions.php line 89
```

**Comment by FamousWolf** [comment]
@Rinxiao Can you check https://github.com/beechit/fal_securedownload/pull/230 to see if that fixes the problem?
