### ISSUE TITLE
Problems when overriding files

### ISSUE THREAD

**Issue by ursforrer** [beechit/fal_securedownload#24]
When I override files via TYPO3 File Manager the extensions, works as it should.
When I override files via FTP or local on the file system the extensions (i think) does not work correctly. The file can not be downloaded and for example in chrome, the error message on the bottom will be displayed. On other browser only a grey background is display.

Error Message: PDF cannnot be display.

**Comment by sonority** [comment]
As far as i know this is not an issue with 'fal_securedownloads' but a problem with TYPO3 (version 6+).
Try to update the storage index (via scheduler task) to reindex the files in your filesystem and update the metadata (filesize) in the database.

**Comment by sonority** [comment]
Another way is to upload the file to a folder outside fileadmin or into a folder which is not automatically indexed by TYPO3 and then, in TYPO3-backend, move the file to the right place. In this case the index is always correct.

**Comment by ursforrer** [comment]
Thanks for your answers. All the folder are outside of the TYPO3 fileadmin folder. So when i disable "Is searchable" in the Capabilities of the file storage it should work?
Otherwise i will try the first case. I had a installation with a filenmanager (simalar the owncloud) to  make the upload process to the user easier. So the second with the backend is no solution.

**Comment by sonority** [comment]
I don't think that disabling "Is searchable" solves the problem, because the file will always be indexed if it is inside a "File Storage" of TYPO3 i think.

Have you tried to reindex the strorage?

**Comment by ursforrer** [comment]
Yes i tried it. It works perfect. The files are displayed correctly after a reindex of the stroage.
Thanks to you for your help.

**Comment by sonority** [comment]
You're welcome!
