### ISSUE TITLE
No Issue but a question: Direct access to protected downloads via URL without login

### ISSUE THREAD

**Issue by stephangrass** [beechit/fal_securedownload#240]
Hello, I have a question: I have taken over a website that was updated to TYPO3 11 after a hack. The developer who did this is no longer reachable.

The client claims that before the update, links to protected downloads (in the form https://url.de/index.php?eID=dumpFile&t=f&f=1234&token=12345678900ea3f35f63), which they inserted into emails, could be opened by email recipients without being logged into the website.

That can't be true, and it also goes against the principle of the extension. Or are there even workarounds for this...

Thanks,
Stephan

**Comment by support-beech** [comment]
@stephangrass 

The original developer isn't working TYPO3 anymore. I've asked around, other developers experienced with this extension find this hard to be true. This would mean it would have been broken. As you say ' it also goes against the principle of the extension'
