### ISSUE TITLE
Problem after updating Typo3 to 11.5.37

### ISSUE THREAD

**Issue by nbyte78** [beechit/fal_securedownload#241]
There seems to be a problem after the Typo3 11.5.37 Update. Version of fal_securedownloads is 5.0.6 The Filemount cannot be found if it is outside the Typo3 root directory. Links are not found anymore in the frontend. Within the Backend nothing on the configuration for the fal_securedownload has changed. 
When looking at the directory sharing on root level it says "Storage "Secure Downloads" is not browsable. No folder is currently selectable."

In the Filelist it says Folder offline and "Base folder for local storage missing or not allowed. Verify that the base folder for the storage "Secure Downloads" exists and is allowed to be accessed."

So i tried to move the folder into the Typo3 root folder. The above problems are gone and i can access the Files within the Backend. When trying to open a link in the Frontend i get the following error:

Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1476107295: PHP Warning: Trying to access array offset on value of type null in xxx/typo3conf/ext/fal_securedownload/Classes/EventListener/ModifyFileDumpEventListener.php line 145 | TYPO3\CMS\Core\Error\Exception thrown in file xxx/typo3_src-11.5.37/typo3/sysext/core/Classes/Error/ErrorHandler.php in line 137. Requested URL: https://xxx/index.php?eID=dumpFile&t=f&f=769&token=--AnonymizedToken--

So what is wrong. Worked without problems for years...

**Comment by nbyte78** [comment]
Observations i made during the testing. The Error (Core: Exeption) only occurs when logged in as Admin in the Backend. When logged out and using a frontend user the files load without Error. But the Directory has to be under the Typo3 Root. Outside it cannot be found.
What i also noticed is that the thumbnails are no longer generated or shown. Don´t know why. Have seen the closed issue. 

Works for normal Frontend User and if the directory is within the root. But doesn´t work when logged in as Admin or with the directory outside the root folder, which it did before.

**Comment by hhjse** [comment]
I had the same problem. For me was the solution to add the path from the protected folder in the configuration "[BE][lockRootPath]"

**Comment by support-beech** [comment]
https://github.com/beechit/fal_securedownload/releases/tag/5.0.7

**Comment by support-beech** [comment]
> I had the same problem. For me was the solution to add the path from the protected folder in the configuration "[BE][lockRootPath]"

Thanks @hhjse
