### ISSUE TITLE
BeforeFileDump Slot is fired twice in some Browsers

### ISSUE THREAD

**Issue by PfefferT** [beechit/fal_securedownload#27]
I am trying to write a download statistic, but the needed Slot (BeforeFileDump) is sometimes double fired, although the browser only sets one http request to get the data.

**Example Browser for this:**
Firefox current version

**Typo3 Version:**
6.2

**Comment by fsaris** [comment]
That is strange as the signal is emitted just before the file contents is pushed to the browser. Are you sure the link isn't called twice? Maybe your browser console creates a second request.
