### ISSUE TITLE
Bug with RTE (TYPO3 6.2)

### ISSUE THREAD

**Issue by audejoly** [beechit/fal_securedownload#30]
Hello,

When i add an image in the RTE with the button 'image', it does not appear that : there is an error because a php file is called and this is not an image element. Is this a bug or configuration problem ?

**Comment by fsaris** [comment]
Sounds like a bug.

**Comment by fsaris** [comment]
Could you maybe post the php error here?

**Comment by audejoly** [comment]
It's not a php error, this is generated code that is the problem : 
<img src="https://www.domain.fr/ajax.php?ajaxID=FalSecuredownload%3A%3ApublicUrl&amp;ajaxToken=9af1cdb0826fa1b3ac9a4d5200ca138f10ae73f5&amp;eID=dumpFile&amp;t=f&amp;f=24677&amp;token=7a74d036d411c98b94e31791f8076a6162508b17" width="602" height="465" data-htmlarea-file-uid="24677" data-htmlarea-file-table="sys_file" />.

**Comment by audejoly** [comment]
i don't know if you can understand ? the code in the attribute "src" is : https://opus.chambres-agriculture.fr/ajax.php?ajaxID=FalSecuredownload%3A%3ApublicUrl&amp;ajaxToken=9af1cdb0826fa1b3ac9a4d5200ca138f10ae73f5&amp;eID=dumpFile&amp;t=f&amp;f=24677&amp;token=7a74d036d411c98b94e31791f8076a6162508b17 and it's not an image code...

**Comment by fsaris** [comment]
If you are logged-in does the url give you an image? Because all IMG tags (front-end and back end) will have such a URL if the file is in a non public storage.

**Comment by audejoly** [comment]
No, when i'm logged-in i don't have an image.
the source code on the frontend is : <img src="ajax.php?ajaxID=FalSecuredownload%3A%3ApublicUrl&amp;amp;ajaxToken=fb100f92ea1766e9863e83a18b073962403658ed&amp;amp;eID=dumpFile&amp;amp;t=f&amp;amp;f=24677&amp;amp;token=7a74d036d411c98b94e31791f8076a6162508b17" width="602" height="465" alt="" style="">

**Comment by svi-berlin** [comment]
Same problem: Try to insert an image in the RTE Textarea results in failure. 

<img src="typo3/ajax.php?ajaxID=FalSecuredownload%3A%3ApublicUrl&amp;amp;ajaxToken=31b55a0d76c5bfbd70b272b9058bee54c50cd8e7&amp;amp;eID=dumpFile&amp;amp;t=p&amp;amp;p=9198&amp;amp;token=752f649ae0a23f61f8d799d76dab3fc249e13a73" hspace="5" vspace="5" border="1" style="" alt="">

In case you call the image src URL directly, you get this error message:

<t3err>
Invalid CSRF token detected for ajaxID "FalSecuredownload::publicUrl"!
</t3err>

**Comment by ianouf** [comment]
Hi,

A normal FE url should be like: mydomain/index.php?eID=dumpFile&t=f&f=9626&token=fa52971d67b7084f2b3b578ec62f4fb2c6c685c8
A normal BE url like: mydomain/typo3/ajax.php?ajaxID=FalSecuredownload::publicUrl&ajaxToken=ff042f9ff77c04f258dc2565629e603168f1584b&eID=dumpFile&t=p&p=181917&token=4878e17447bed274ff3d1553e1e6ab51e69680b1

The probleme is in the RTE, the url is neither, but like:
mydomain/ajax.php?ajaxID=FalSecuredownload%3A%3ApublicUrl&ajaxToken=28882de64d543680bcce40c77e6fd0bba4fc9039&eID=dumpFile&t=f&f=9626&token=0c093792eab19df128d4e51517b561f6d662ac81

It's a BE url without the /typo3/ segment.

I think the most important should be the FE rendering, so the url has to be from the first type.
Even if we can't see the image in the RTE, in the BE.
But it should be possible to do like the DAM did: 
`<file id="6545461"> ` in the database for RTE, and render it in two different way in BE and FE.

**Comment by fsaris** [comment]
This is a TYPO3 core issue. This extension uses the non-public storage handling of the core.

To be sure, could you test this by disabling/de-install fal_securedownload, keep the storage non-public and add an image to the rte.

BTW: FAL uses just like DAM tags with an id

**Comment by ianouf** [comment]
Hi, actually i made the test.
In the RTE, without fal_securedownload, and with an image in a non-public storage, i got this URL:
http://mydomain/index.php?eID=dumpFile&amp;t=f&amp;f=934&amp;token=b50cb9a405aebd8d3a399830b3b953646af0a55a

It's typicaly a FE url , with index.php, and not ajax.php like i got with fal_securedownload.

**Comment by fsaris** [comment]
Tnx for testing. Then I probably know where to search for the issue

**Comment by audejoly** [comment]
Hello, did you know when you will fix this issue ?

**Comment by frans-beech-it** [comment]
Just tested with 7.6.11 and there it just works as expected.

No time yet to look at 6.2.

**Comment by frans-beech-it** [comment]
In BE you get an image tag like `<img src="http://site.typo3.local/typo3/index.php?ajaxID=FalSecuredownload%3A%3ApublicUrl&amp;eID=dumpFile&amp;t=p&amp;p=92&amp;token=fbd20c4313e384daf3e9f0f5e6455964063867fa&amp;ajaxToken=54ee33333333ddb1ba6a4c8269a4fa3f57b2df" width="300" height="201" alt="" data-htmlarea-file-uid="38" style="" />` and in FE `<img src="index.php?eID=dumpFile&amp;t=p&amp;p=92&amp;token=8222befaf1ab53c39d1fe9184bb1d9e6e030dab" width="300" height="201" alt="" style="" title="">`

In BE the `data-htmlarea-file-uid="38"` holds the file uid. Make sure the RTE config doesn't strip this tag.

**Comment by goodsdorak** [comment]
Hi,
I've the same problem with the version 7.6.16 (image not available for non public folder)

I tried to comment in class PublicUrlAspect::generatePublicUrl the definition of $urlData['publicUrl']

The src is now as a standard image src and the rights are always available !

So why this transformation ? For me it's enough ....
Maybe can you add an option to not change url ?


In any case thanks for your extension ;) 

Seb

**Comment by frans-beech-it** [comment]
Are you on latest version? could you maybe post the `<img` tags that's created with and without the line commented out.

The reason for the transformation is to enable preview for access restricted files for the editor that isn't logged-in in the FE with correct access permissions for the particular file/image.

**Comment by frans-beech-it** [comment]
BTW: does't it work in FE or BE?

**Comment by goodsdorak** [comment]
Yes I'm in the last version proposed by the TER (1.2.1).

tag with the standard extension : 
BE : 
`<img alt="" data-htmlarea-file-uid="1241" height="26" width="26" src="https://mysite/typo3/index.php?ajaxID=FalSecuredownload%3A%3ApublicUrl&amp;eID=dumpFile&amp;t=f&amp;f=1241&amp;token=6062552f62907c50317717296d0a99fca9b4cd57&amp;ajaxToken=1353b5f5baaf1fee384666889ed8eb9240191e40" style="" />`
=> FE
`<img alt="" height="26" width="26" src="typo3/index.php?ajaxID=FalSecuredownload%3A%3ApublicUrl&amp;eID=dumpFile&amp;t=f&amp;f=1241&amp;token=6062552f62907c50317717296d0a99fca9b4cd57&amp;ajaxToken=1353b5f5baaf1fee384666889ed8eb9240191e40" style="">`

If my FE account is allowed to see an image, I can see it in BE, I can'T see it in FE. 
If my FE account is NOT allowed to see an image, I can see it in BE, I can'T see it in FE. 

tag with commented line : 
BE : 
`<img alt="" data-htmlarea-file-uid="1241" height="26" width="26" src="https://mysite/index.php?eID=dumpFile&amp;t=f&amp;f=1241&amp;token=2e51e62e894cee7c4f6f9852f444732556321c8c" style="" />`
=> FE
`<img alt="" height="26" width="26" src="index.php?eID=dumpFile&amp;t=f&amp;f=1241&amp;token=2e51e62e894cee7c4f6f9852f444732556321c8c" style="">`

In BE and FE, I can see the image.
If my FE account is allowed to see an image, I can see it in BE, I can see it in FE. 
If my FE account is NOT allowed to see an image, I can'T see it in BE, I can'T see it in FE.

**Comment by kazmataaz** [comment]
Hi,
I have exactly the same problem TYPO3 7.6.18 and fal_secure_download 1.2.2
Picture added in the RTE get an ajaxID=FalsecureDownload and don't show in the browser
