### ISSUE TITLE
Can't add files or folder

### ISSUE THREAD

**Issue by thombeck** [beechit/fal_securedownload#31]
Hi
With TYPO3 7.6.4 and last fal_securedownload version, I can't add files or folder in the Fal secure download folder. Pictos are unavailable.

Any help is welcome !

Thanks 
![capture](https://cloud.githubusercontent.com/assets/15835008/14283263/e9845a6c-fb42-11e5-9495-f8d085130fbf.jpg)

**Comment by camrun91** [comment]
I am having the same issue 
![capture](https://cloud.githubusercontent.com/assets/16566029/14297764/2ed49642-fb46-11e5-87c2-c4d0b9d135e1.JPG)

**Comment by beechit** [comment]
Could you test the current git master? That should fix this issue

**Comment by beechit** [comment]
thombeck is the "Is writable?" checkbox checked in the storage record? And is the folder writeable for the webserver user?

![image](https://cloud.githubusercontent.com/assets/1887364/14322384/fe975f32-fc1c-11e5-9145-c909f81314ac.png)

**Comment by thombeck** [comment]
It works with the 1.0.2 version
Thanks !
