### ISSUE TITLE
Folder permission Icon missing in 6.2

### ISSUE THREAD

**Issue by pitscribble** [beechit/fal_securedownload#32]
Since I updated to version 1.0.1 the folder permission icon in the Filelist-Module in our 6.2 installation is missing and instead shows the red-questionmark-icon. Still the same in 1.0.2.

**Comment by beechit** [comment]
Hi pitscribble,

we just pushed a fix 5944f4a90f6dc4b19f1a10aa4a07c744fca45417 could you test if this resolves your issue?

**Comment by pitscribble** [comment]
Yes, the item is back. Thanks a lot!
