### ISSUE TITLE
MS Office download ask for login

### ISSUE THREAD

**Issue by gaumondp** [beechit/fal_securedownload#33]
Maybe it's server related but it looks like the files are not sent using some kind of "ForceType application/octet-stream" or "Header set Content-Disposition attachment" and it makes Word and Excel files to ask for login/password in intranet environment.

I tried adding this in .htaccess without success for an Excel file : 
<FilesMatch "\.(?i:xlsx)$">
  ForceType application/octet-stream
  Header set Content-Disposition attachment
</FilesMatch>

Maybe adding this (http://php.net/manual/fa/function.http-send-content-disposition.php) would make FAL SecureDownload works but sadly it's from PECL module.

If our files are under /fileadmin/ everything works as expected.

**Comment by fsaris** [comment]
Could you maybe test if it works when you disable the FE compression?

`$TYPO3_CONF_VARS[‘FE’][‘compressionLevel’] `

**Comment by gaumondp** [comment]
Sadly [‘FE’][‘compressionLevel’] is already at 0.

**Comment by fsaris** [comment]
could you try to add `&download=1` to the url?

**Comment by gaumondp** [comment]
Then it works ! I had to add it directly in the address bar of IE (didn't work in RTE source):

So using the link in the URL bar worked : 
"https://mysite.com/index.php?eID=dumpFile&t=f&f=377&token=2ed66dea754037faed5884a2a59204d72a3a771d&download=1"
