### ISSUE TITLE
Add option to always force download

### ISSUE THREAD

**Issue by gaumondp** [beechit/fal_securedownload#35]
In the case of MS-Office files it is possible Excel or Word ask for User/Password when reached thru IE11. If you add &download=1 to Fal Secure Download (FSD) generated links IE11 will not try to let Excel open it and generate dialog box so it would be great to have one of those 2 options : 

1. In EM for the extension, get a boolean like : 
Always force downloadd = 0/1

2. In EM have a field to enter file extensions to force download.
Force download for these file extensions = xls,xlsx,doc,docx

**Comment by mgrn0** [comment]
any update on this? is there an option to add "&download=1" to all file links by default that I did miss?

**Comment by gaumondp** [comment]
@mgrn0 , there's a manual workaround possible that involve modifying the extension. 

Use at YOUR OWN RISK !

I am not a developer and can't support you if something goes wrong.

File:https://github.com/beechit/fal_securedownload/blob/master/Classes/Hooks/FileDumpHook.php#L106

change:
```
        if (isset($_REQUEST['download'])) {
            $file->getStorage()->dumpFileContents($file, true);
            exit;
        }
```

to

``` 
           $file->getStorage()->dumpFileContents($file, true);
            exit;
```

**Comment by marvinschroeder** [comment]
+1 for config option to force download!
