### ISSUE TITLE
Safari: can not open protected files

### ISSUE THREAD

**Issue by MrJack91** [beechit/fal_securedownload#36]
Hi Frans Saris

First, thanks for your work.

I found a strange behavior in Safari:
Safari (on iPad iOS 9.3 and OS X OS X 10.11.4) cannot open files (for example .mp3) protected with _fal_securedownload_ who are only available for fe_users. If the folder has no limitation (but is also not public) all is working fine.
The problem occurs with Safari (and IE 11 / Edge).
Chrome, Firefox, Opera are working.

I've created a small test page: [http://test76.laupercomputing.ch/fal-securedownload/](http://test76.laupercomputing.ch/fal-securedownload/)
Using: Typo3 7.6.6 (same behavior with Typo3 6.2.21), fal_securedownload 1.0.2
It's two times the same mp3-File.

The header data for both requests are looking equal...
Do you have any idea?

Best regards, michael

**Comment by fsaris** [comment]
Issue looks similar to  #35, could you maybe test to see if that fixes your issue to?

**Comment by MrJack91** [comment]
Thank you for your answer.

No it's not the same issue. I do not want to download the file, it should only open in a new tab and play the mp3.

If you go to my testsite with safari, you will see:
- first file works
- second file: player appears, error: missing plugin

**Comment by beechit** [comment]
The strange thing is that both files got through the same `dumpFileContents()` code. fal_securedownload only prevents the core from calling `dumpFileContents()` and outputting anything when there are insufficient rights for the user to access the file.

If you switch the 2 files you get still the same results? And the same for other mp3 files?

**Comment by MrJack91** [comment]
Both files are identical. If I switch the permissions of the two test folders (with access / without access), it's the same behaviour only inverted.
So I think it must be something in your code. But it occurs only in Safari.

Are there no others with the same issue?
I've spot this on a customer website, and also on a new plain typo3 v7.6.6 (the test site).

**Comment by fsaris** [comment]
This is an Safari issue. It can not handle the secured file stream handled by PHP. 
For some more insides see http://stackoverflow.com/questions/3114406/single-php-exit-statement-prevents-html5-video-in-safari/3125869#3125869

I know @liayn   worked on a feature that has a different approach for the PHP stream maybe that's also a solution for this Safari issue.

**Comment by liayn** [comment]
If I understand SO correctly, Safari does 2 requests on the same base-url, where the second one fails to send cookies. My approach involves a redirect from the eID URL to a static file (a symlink to the actual resource). I fear that this won't work either.

**Comment by fsaris** [comment]
We would need to test this but I expect that Safari passes the result of the redirect to the player. If that's true it would work

**Comment by liayn** [comment]
Indeed.
aside from that I spent some hours on reading again and found that `header("Cache-Control: ''");` in Core is probably not optimal. (`\TYPO3\CMS\Core\Resource\ResourceStorage::dumpFileContents`)

**Comment by frans-beech-it** [comment]
closed for now. Once there is a proper solution in the core we can use that
