### ISSUE TITLE
Make FileDumpHook::feUser public

### ISSUE THREAD

**Issue by lorenzulrich** [beechit/fal_securedownload#37]
The signal in the FileDumpHook is most likely used to do something like logging. For logging, the authenticated Frontend User may be required. Since we are in eID context, this is not present by default in `GLOBALS['TSFE']`. By making `FileDumpHook::feUser` public, it would be accessible from within the slot.

**Comment by fsaris** [comment]
Could you create a pull request that adds public getFeUser() method?
