### ISSUE TITLE
PublicUrlAspect should respect Folders

### ISSUE THREAD

**Issue by johannessteu** [beechit/fal_securedownload#38]
If you use the ext `my_user_management` a public url for a folder is requested. The Current implementation only respects files.

![screen shot 2016-06-14 at 11 08 10](https://cloud.githubusercontent.com/assets/769789/16037503/1577cf54-3221-11e6-85f7-79d06e064cf3.png)

**Comment by fsaris** [comment]
Could you try the current master? This should be fixed there 

Gr. Frans

**Comment by johannessteu** [comment]
@fsaris is there already a new release that fixes this issue? We got still the problem, can't deploy dev-master here, sorry

**Comment by frans-beech-it** [comment]
Just tagged version 1.0.3

**Comment by johannessteu** [comment]
@fsaris will it be pushed automatically to the ter? 1.0.2 is tere still the latest release. Otherwise i'll use the github source instead in my composer.json

**Comment by fsaris** [comment]
Just require `beechit/fal-securedownload` in your composer.json. It is now available on packagist.
