### ISSUE TITLE
Secure downloads without plugin

### ISSUE THREAD

**Issue by oliverbeck** [beechit/fal_securedownload#39]
Hi

This is just a question: Is it possible to provide secure download link without the provided plugin? I have some file list (CType uploads) with file references, is it possible to create secure downloadlinks just with fluid? 

Kind reagrds, oliver

**Comment by frans-beech-it** [comment]
Yes, once the extension is installed all links to files that are in a "secure" folder get the special url.
The provided plugin isn't needed for that. At least if you use the proper FAL API. So in fluid use `{file.publicUrl}`

gr. Frans

**Comment by oliverbeck** [comment]
unfortunately it doesn't work for me. I've followed the three installation steps: install extension, create non-public storage, set permission on folder and create an .htaccess file with deny from all. the download links in my fluidtemplate of CType uploads looks like this:

`<a href="{file.publicUrl}" target="_blank">{file.properties.title}</a>`

but the links are rendered the "normal" way and I get 403 forbidden, although I'm logged in as the correct user.

thanks for any hint

**Comment by frans-beech-it** [comment]
strange, no page cache or something?

Once a storage is set to "non public" all links get a FileDump url so even without fal_securedownload you should get a different url.

**Comment by oliverbeck** [comment]
solved!

Here is my fault: I've created the non-public storage inside another public-storage. The non-public storage has to be standalone.

Thanks allot =)
