### ISSUE TITLE
Export of TYPO3 pages to t3d throws exception

### ISSUE THREAD

**Issue by einpraegsam** [beechit/fal_securedownload#42]
Easy to reproduce in TYPO3 7.6:
Just click on a page with right mouse key and choose branch-actions/Export to t3d:

`Oops, an error occurred!

PHP Catchable Fatal Error: Argument 3 passed to BeechIt\FalSecuredownload\Aspects\PublicUrlAspect::generatePublicUrl() must be an instance of TYPO3\CMS\Core\Resource\FileInterface, instance of TYPO3\CMS\Core\Resource\Folder given in /xxx/releases/current/Web/typo3conf/ext/fal_securedownload/Classes/Aspects/PublicUrlAspect.php line 79`

Used version of fal_securedownload: 1.0.2

**Comment by beechit** [comment]
Hi Alex,

this is fixed in the new version of fal_securedownload.

**Comment by einpraegsam** [comment]
Ok, thx for the note.
Where can I find the changelog?
I want to look inside before updating...

**Comment by frans-beech-it** [comment]
Change log can be found here
https://github.com/beechit/fal_securedownload/compare/1.0.2...1.1.0

Op di 19 jul. 2016 14:12 schreef Alex Kellner <notifications@github.com>:
