### ISSUE TITLE
Permissions for shared folders of directory

### ISSUE THREAD

**Issue by angeloprevitali** [beechit/fal_securedownload#51]
We got three storage folders configured to a BE user group "Redaktoren". If a BE user loggs in and would like to add a file tree to be displayed in the FE currently there is NO restrictions of the storage folders which he gets granted. He always see every folder to choose. It should be NOT.

Can you fix this?

Thanks.

Regards,
Angelo

![screenshot-2016-08-02-14-00-35](https://cloud.githubusercontent.com/assets/17588253/17327672/ae9c6b4a-58b9-11e6-87d3-9af79de9e74a.png)

![screenshot-2016-08-02-14-00-45](https://cloud.githubusercontent.com/assets/17588253/17327671/ae9b742e-58b9-11e6-8844-19869496d23d.jpg)

**Comment by fsaris** [comment]
I think you mixing file storage with file mount.

You can restrict access to a certain file mount. But the option the editor selects in the plugin settings is the file storage.

Nevertheless how should the form behave when editor 1 sets a certain storage + folder. And now editor 2 edits the same plugin but he isn't allowed to select that storage + folder?

**Comment by angeloprevitali** [comment]
Should be as you described, YES - but it doesn't work! 

If you open a BE group you can grant the file storage to a certain group of editors but it has no effect on the BE group. The BE group still has access to every filemount created. Take a look to the configuration of the BE group in the image.

![screenshot-2016-08-03-08-24-08](https://cloud.githubusercontent.com/assets/17588253/17355861/fa3ef672-5953-11e6-84c3-f07f7570ae84.png)

I really think that it is a "bug".

**Comment by angeloprevitali** [comment]
I installed your great extension on a brandnew TYPO3 CMS version 8.5.1 and I got still the same problem as described in the older tickets and I don't know how to solved it. How can be a editor be set upped that he just sees the folders which he gets access on the filmounts? Currently it seems he sees the whole filestorage that are configured. Any idea how to set up this?

Thanks for help.

Regards,
Angelo

**Comment by angeloprevitali** [comment]
By adding the following line in the Flexform the permission problem could be resolved.

FilTree.xml file before:
`<foreign_table_where>ORDER BY sys_file_storage.name</foreign_table_where>`

After that fits with the actual permissions of the editors permissions
`<foreign_table_where>AND sys_file_storage.is_default = 0 ORDER BY sys_file_storage.name</foreign_table_where>`

What do you think about it?

Thanks for your feedback.

Regards,
Angelo

**Comment by fsaris** [comment]
This only excludes the default storage so that's no real solution. We need to make sure that only folders are shown where the editor has access to.

How does this work for the sys_file_collections used by the files/upload content element?

**Comment by angeloprevitali** [comment]
That is correct. It should be something like this:

`<foreign_table_where>AND sys_filemounts.base = sys_file_storage.uid ORDER BY sys_file_storage.name</foreign_table_where>`

but I don't know how you make a SELECT over multiple tables in Flexform.

Do you?

**Comment by angeloprevitali** [comment]
This issue has been fixed on the actual TYPO3 CMS version 8.7.12. It seemed to be a bug from TYPO3 and NOT from the EXT:fal_securedownload.

So I close this issue.

**Comment by fsaris** [comment]
Tnx for the feedback
