### ISSUE TITLE
Compatibility of fal_securedownload with TYPO3 CMS version 8.5 and higher

### ISSUE THREAD

**Issue by angeloprevitali** [beechit/fal_securedownload#61]
Could you adapt/fix the compatibility of fal_securedownload with the actual TYPO3 CMS version of 8.5 and higher?

That would be great.

Thank you very much.

Regards,
Angelo

**Comment by frans-beech-it** [comment]
Fix is currently in the making https://github.com/beechit/fal_securedownload/pull/59

Or do you encounter other issues?

**Comment by angeloprevitali** [comment]
No. I mean just this. BUT, due to TYPO3 version 8.5 and higher new restrictions the TYPO3 accepts no longer extension that aren't fully compatible with 8.5 the installation throws an error on installing your extension. Can you pulbish a working one on TER?

**Comment by fsaris** [comment]
New version has been released that's compatible with 8.5.

**Comment by angeloprevitali** [comment]
Guten Tag

Ich bin bis und mit Sonntag, 26. Februar 2017 abwesend. 

Ihr E-Mail wird nicht weitergeleitet und erst am Montag, 27. Januar 2017 gelesen.

In dringenden Fällen kontaktieren Sie Herr Ernest Peter (ernest.peter@netconsult.ch, Tel.  031 352 01 48).

Besten Dank.


Freundliche Grüsse
Angelo Previtali

Angelo Previtali
TYPO3 CMS Integrator

NetConsult AG
Buristrasse 21, 3006 Bern
Tel. 031 352 01 48
angelo.previtali@netconsult.ch
www.netconsult.ch
