### ISSUE TITLE
CheckPermission overwrites variable

### ISSUE THREAD

**Issue by madaxel** [beechit/fal_securedownload#64]
In BeechIt\FalSecuredownload\Security\CheckPermissions.php
Line 117 the $folder 
`			foreach ($this->getFolderRootLine($folder) as $folder) {
				// fetch folder permissions record
				$folderRecord = $this->utilityService->getFolderRecord($folder);
`
variable seems to be overwritten. I'm not quiet sure if it has any bad impact here, cause it is not used afterwards, but if not needed I would recommand to change var name here.

**Comment by fsaris** [comment]
Would be cool if you could provide a PR for this

**Comment by madaxel** [comment]
Tried to #66
