### ISSUE TITLE
Leaf.html and fluid

### ISSUE THREAD

**Issue by madaxel** [beechit/fal_securedownload#65]
typo3conf/ext/fal_securedownload/Resources/Private/Partials/FileTree/Leaf.html
Line 6
`<span class="icon-folder {sd:leaveState(folder:'{subFolder}', then:'icon-folder-open')}"`
seems to be wrong.
<span class="icon-folder {sd:leaveState(folder:{subFolder}, then:'icon-folder-open')}"
would be better, because the ' will cause a fluid to think of subFolder being a sting (use htmlspecialchar(subFolder))

**Comment by fsaris** [comment]
Would be cool if you could provide a PR for this
