### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by farconada** [beechit/fal_securedownload#72]
Would you mind to ask to the TYPO3 team to add this extension to translation server. I want to translate it to spanish.
https://forge.typo3.org/issues/80137
I did it already but I think that the request should come from the owner

Thanks

**Comment by fsaris** [comment]
Maybe it's easier to just add the translations to the extension. If you create a PR we will add them.

**Comment by farconada** [comment]
already translated in translation.typo3.org

**Comment by fsaris** [comment]
Ah, nice.
