### ISSUE TITLE
Error Adding Files to content

### ISSUE THREAD

**Issue by kazmataaz** [beechit/fal_securedownload#80]
An "error 200" popup when any user try to add an image from a "Fal secured" directory/ File Storage
and the image/media file does not get attached to the content element.
Typo3 7.6.18/ Fal_securedownload 1.2.2

**Comment by frans-beech-it** [comment]
error 200 doesn't say that much. is there more info in the error log or in the browser console?

**Comment by kazmataaz** [comment]
i get an Syntaxerror: JSON.parse: unexpected  character at line 1 column 1 of the JSON data message when I look at the Browser Console

**Comment by fsaris** [comment]
Can you check the response in the network tab? Looks like you run into a server side error

**Comment by kazmataaz** [comment]
I checked the response
and the only difference to a response i get from adding a picture out of a public storage  it is
starting with the following line
` `

and then  
`{"data":"\n\t\t\t\t<div class=\"panel panel-default panel-condensed panel-visible inlineIsNewRe
cord\" id=\"data-6275-tt_content-27369-assets-sys_file_reference-NEW591626df0a8a4587945651_div\">` etc... 
and it seems ok for me...do you want me to send you the full response

**Comment by kazmataaz** [comment]
When Adding Files directly to the filestorage, it says that the file upload failed but the file gets uploaded

**Comment by frans-beech-it** [comment]
Without ext:fal_securedownload installed you also get this error?

**Comment by kazmataaz** [comment]
When i deinstall fal_securedownload there is no error. Uploading and attaching images works without any error

**Comment by kazmataaz** [comment]
upgrade to fal_securedownload 1.2.3 solves this problem

**Comment by ZYZ64738** [comment]
The extension "debug_mysql_db (0.6.0)"  causes this errormsg too:

https://domainname/"//typo3//sysext//core//Resources//Public//Icons//T3Icons//mimetypes//mimetypes-media-image.svg/"
