### ISSUE TITLE
PDF not viewable in browser

### ISSUE THREAD

**Issue by kazmataaz** [beechit/fal_securedownload#81]
PDF that gets delivered by fal_securedownload as eID dumpfile cannot be viewed in Browser, only download

**Comment by frans-beech-it** [comment]
this is probably not related to fal_securedownload. Only if you forced the download of files in the extension configuration (see extension manager).

It is known that not all browsers support inline view when files are provided by a proxy (the PHP layer that serves the file). Could be related to wrong headers send. In what browser(s) did you experience this behavior?

**Comment by kazmataaz** [comment]
thank you , it was due the force_download option
