### ISSUE TITLE
Different file dumping on different mime types?

### ISSUE THREAD

**Issue by FireLizard** [beechit/fal_securedownload#85]
Hello,
I've got an unexpected behaviour:

Inside my default file storage (fileadmin/) i've uploaded an image and an pdf-document. Both are restricted to a previously generated FE-Group named "intern". The storage is set as _non-public_ and secured by _.htaccess_ (`Require all denied`).

Now when adding a _text & media_ element to a site and link the image and pdf-document as media then both are not accessible as long as the visitor is not a member of group "intern". :+1:
When linking the image and pdf-document as a text-link via RTE then only the access of the image is denied. :-1:

Thanks 4 reply!

Greetings
FireLizard

**Comment by fsaris** [comment]
How do the links generated by the rte look like?

**Comment by FireLizard** [comment]
Version of TYPO3 is 7.6.18

BE
```html
<ul>
  <li>
    <a href="http://localhost/typo3/web/?file:331">image</a>
  </li>
  <li>
    <a href="http://localhost/typo3/web/?file:306">pdf</a>
  </li>
</ul>
```
FE
```html
<ul>
  <li>
    <a href="/typo3/web/index.php?eID=dumpFile&amp;t=f&amp;f=331&amp;token=c6ad01f92c00fc5e70d1288b44032113db4ec599" target="_blank">image</a>
  </li>
  <li>
    <a href="/typo3/web/index.php?eID=dumpFile&amp;t=f&amp;f=306&amp;token=3f29f6d609c63f0acf30263c353c2eb99b70b38d" target="_blank">pdf</a>
  </li>
</ul>
```

**Comment by frans-beech-it** [comment]
And you are sure file `306`  is restricted? as the url looks ok.

**Comment by FireLizard** [comment]
Ok, I think I found it out.
**It has nothing to do with the mime type** (would have been quite funny)

Steps to reproduce accessible files though set group restriction:
1. upload a new file or select one without previously set group access
2. call webpage that's including this file (I guess it will generate the _dumpFile_-URL)
3. restrict access by assigning a group
3. as an unauthorized user it should display "Authentication required!". But it don't!

So when the file is not requested by an unauthorized user the very first time then all following requests are going to granting access.

Seems to me, that an already generated _dumpFile_-URL maybe is not reevaluate the current restrictions (and is cached anyway?).

**Comment by frans-beech-it** [comment]
can you try to access such a link in a different browser or with all browser cache cleared?

**Comment by FireLizard** [comment]
Hmm? -.- Yeah ok...
+1 for the browser cache hint ;)

Thank you!
