### ISSUE TITLE
Wrong file size after ftp upload

### ISSUE THREAD

**Issue by Rumpelstielzchen** [beechit/fal_securedownload#86]
Using fal_securedownload v1.2.3 with typo3 7.6.18. 
After uploading via FTP, some files have the wrong size.
This causes images to not be displayed completely and can not be fully downloaded. 
Empty all caches does not improve.

**Comment by frans-beech-it** [comment]
Not sure if this is related to ext:fal_securedownload. As it just uses the core api to output the files contents.

Did you test this without the extension installed but with the storage set to non-public. As the file output handling should also go through the same core API
