### ISSUE TITLE
adding a counter for downloaded files by fe-user/ -group

### ISSUE THREAD

**Issue by mm-baer** [beechit/fal_securedownload#9]
it would be nice to have a backend-module to show who has downloaded a file (by FE-User/ FE-Group)

**Comment by liayn** [comment]
I will implement this feature now. We need it for a customer and Frans agreed to have it in this ext.
Concept is:
* Feature for CMS 7 only
* Feature can be enabled in Extension Configuration in Extension Manager
* DB-Table to store a record for each download with sys_file uid and fe_users uid
* FormEngine Node for fe_users to show downloads of a user there.

**Comment by tliegl** [comment]
Would be nice, if this statistic could also track downloads of non-secured files when no fe_user is active, e. g. a normal pdf link on a website.

**Comment by liayn** [comment]
That is out of scope of this feature. Normal pdf links are directly accessed by the webserver and no PHP code is involved. Hence, that's not possible.

**Comment by lorenzulrich** [comment]
We did that a while ago: https://github.com/visol/ext-download_stats

**Comment by liayn** [comment]
Thanks for sharing. Will take a look and possibly incorporate your ext then directly.
