### ISSUE TITLE
internal image processing does not work

### ISSUE THREAD

**Issue by metiny** [beechit/fal_securedownload#91]
I have a file storage for fal_securedownload. 
Driver: Local filesystem, Path: absolut

Everything works perfect. Only the TYPO3-internal image processing does not work. I create a "New Relation" to an image from the file storage, BE and FE works as expected. In BE with "Open Editor" the workspace remains empty without a message. The small preview window on the top right shows a "corrupt" icon.

TYPO3 8.7.8
fal_securedownload 2.0.1

**Comment by frans-beech-it** [comment]
Fixed with #98
