### ISSUE TITLE
Files from secured folder can still be downloaded without plugin

### ISSUE THREAD

**Issue by emileblume** [beechit/fal_securedownload#95]
In version 2.0.1 with TYPO3 8.7.10 I've added secure folders, files in here should only be accessible when a frontend user is logged in. In the Fileadmin I can see the folders have the correct icon and are connected to a specific FE Usergroup. When I try to access one of these files in an anonymous browser-window I can download the secured files anyhow. We are having clients who depend on this, now their files are accessible by anyone.

**Comment by fsaris** [comment]
Hi,

how do the links to the files look like that are directly accessible?

**Comment by emileblume** [comment]
Hi, the links themselves do not show a path. Once someone finds out what path to use the file was accessible. The problem is solved with some help. The explanation on how to use this wasn't clear to me and could be better in my opinion.

**Comment by fsaris** [comment]
Hi, tnx for you feedback.

We are open to merge any PR that improves the documentation :)

**Comment by emileblume** [comment]
Hi Frans,

If I find the time I will send you a bit of documentation for less experienced users, like myself.

Cheers,
Emile

Netcreators
 
E: emile@netcreators.nl
T: 026 442 1950
I: www.netcreators.nl
 
Bezoekadres
Klarendalseweg 71
6822GB  ARNHEM
--------------------------------------------------
Linkedin: www.linkedin.com/company/netcreators-bv
Facebook: www.facebook.com/netcreators
Twitter: @netcreatorsnl
=====================================================
Professional CMS support voor Typo3, Drupal, Magento & WordPress
=====================================================
