### ISSUE TITLE
Audio Download with html5 audio Tag fails after a few minutes

### ISSUE THREAD

**Issue by frankschuessler** [beechit/fal_securedownload#96]
I have build a html5 audio player content element which renders a audio tag with up to 3 filetypes (mp4/m4a, mp3 and ogg).
I stored these files in a secured filestorage and link them via IRRE as FAL relations in my CE.
The source looks fine, the eID script is triggered, urls are piped through the eID Script and the files starts to stream, logging mechanism logs the file request.
After a few seconds the Player just stops and begin to play the file from the beginning and i am not able to go for or backward in the audio controls.
An other behavior i recognized is, that the audio player shows a string called "Livestream". 

If i include the files from a non secured storage the duration of the audio file is displayed and controls behave as expected as well as the playback runs till the end.

Any ideas on this behavior? Maybe there is a problem with session timeout/configuartion or something like this?

Thanks in advance for your investigation and for sharing this nice extension!

TYPO3 8.7.10
fal_securedownload 2.0.1

**Comment by beechit** [comment]
Hi,

could you try https://github.com/beechit/fal_securedownload/releases/tag/2.1.0 maybe the resumable download part fixes this issue.

Regards,
Frans

**Comment by frankschuessler** [comment]
Hey Frans,

thank you for the update, seems to fix the problem.
