### ISSUE TITLE
Uncollapsed folder tree is always collapsed after reload

### ISSUE THREAD

**Issue by vixe76** [beechit/fal_securedownload#97]
I have the problem that the folder tree which was uncollapsed before (LeafStates are all correctly set) is always completly collapsed after reloading the page or after leaving the page and navigate to the page again. Are all caches cleared then it works once time again (tree is uncollapsed). It works once only immediately after clearing all caches.  The frontend cache is disabled so it seems to be the system cache!?

Best Falk

TYPO3 v8.7.10
EXT:fal_securedownload v2.1.0

**Comment by PureDude** [comment]
I have the same problem (TYPO3 8.7.10, FALSecureDownLoad 2.1.0). Leaf-states are set correctly but the uncollapsed tree is displayed only once when all caches are cleared. Frontend cache for relevant page is disabled.

Best regards, Stephan

Btw... nice extension!

**Comment by fsaris** [comment]
Your experiencing this issue only for anonymous user's? So no FE user logged in?

**Comment by fsaris** [comment]
Strange the tree is a non-cacheable action.
Shouldn't be cached at all. Could you check what headers are send to the browser? Check if there is a cache header

**Comment by PureDude** [comment]
FE user is logged in! I think it has not to do with the cache header. Because the tree is really uncached. If I put a new file under the storage it also appears immediately in the frontend. This works perfect. But the viewhelper `{sd:leaveState(folder:subFolder, then:'open')}` only once returns correct status if all caches have been emptied immediately.

**Comment by fsaris** [comment]
Ah, probably due to changes in `AbstractConditionViewHelper`.

We need to adjust the viewhelper to be inline with these changes

**Comment by beechit** [comment]
Could you test https://github.com/beechit/fal_securedownload/releases/tag/2.1.1 to see if this fixes the issue for you?

**Comment by PureDude** [comment]
It solves the problem! Thx for the update!
